version: '3.8'

services:
  gowa-admin:
    build:
      context: .
      dockerfile: docker/golang.Dockerfile
    ports:
      - "8088:8088"  # Admin API port
      - "3001-3010:3001-3010"  # Range for GOWA instances
    environment:
      # Admin API Configuration
      ADMIN_TOKEN: "change-this-to-a-secure-token"
      SUPERVISOR_URL: "http://127.0.0.1:9001/RPC2"
      SUPERVISOR_USER: "admin"
      SUPERVISOR_PASS: "change-me-now"
      SUPERVISOR_CONF_DIR: "/etc/supervisor/conf.d"
      INSTANCES_DIR: "/app/instances"
      SUPERVISOR_LOG_DIR: "/var/log/supervisor"
      GOWA_BIN: "/usr/local/bin/whatsapp"
      GOWA_BASIC_AUTH: "admin:admin"
      GOWA_DEBUG: "false"
      GOWA_OS: "Chrome"
      GOWA_ACCOUNT_VALIDATION: "false"
      LOCK_DIR: "/run"
      
      # Admin Server Configuration
      ADMIN_DEBUG: "true"
    volumes:
      - instances_data:/app/instances
      - supervisor_conf:/etc/supervisor/conf.d
      - supervisor_logs:/var/log/supervisor
      - supervisor_run:/run
    command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Admin server as a separate service (alternative approach)
  gowa-admin-server:
    build:
      context: .
      dockerfile: docker/golang.Dockerfile
    ports:
      - "8088:8088"
    environment:
      ADMIN_TOKEN: "change-this-to-a-secure-token"
      SUPERVISOR_URL: "http://gowa-supervisor:9001/RPC2"
      SUPERVISOR_USER: "admin"
      SUPERVISOR_PASS: "change-me-now"
      SUPERVISOR_CONF_DIR: "/etc/supervisor/conf.d"
      INSTANCES_DIR: "/app/instances"
      SUPERVISOR_LOG_DIR: "/var/log/supervisor"
      GOWA_BIN: "/usr/local/bin/whatsapp"
      GOWA_BASIC_AUTH: "admin:admin"
      GOWA_DEBUG: "false"
      GOWA_OS: "Chrome"
      GOWA_ACCOUNT_VALIDATION: "false"
      LOCK_DIR: "/run"
      ADMIN_DEBUG: "true"
    volumes:
      - instances_data:/app/instances
      - supervisor_conf:/etc/supervisor/conf.d
      - supervisor_logs:/var/log/supervisor
      - supervisor_run:/run
    command: ["/usr/local/bin/whatsapp", "admin", "--port", "8088"]
    depends_on:
      gowa-supervisor:
        condition: service_healthy
    profiles:
      - separate-services

  # Supervisor daemon as a separate service
  gowa-supervisor:
    build:
      context: .
      dockerfile: docker/golang.Dockerfile
    ports:
      - "3001-3010:3001-3010"  # Range for GOWA instances
      # Note: Do NOT expose port 9001 publicly in production
    environment:
      SUPERVISOR_USER: "admin"
      SUPERVISOR_PASS: "change-me-now"
    volumes:
      - instances_data:/app/instances
      - supervisor_conf:/etc/supervisor/conf.d
      - supervisor_logs:/var/log/supervisor
      - supervisor_run:/run
      - ./docs/features/supervisord.conf:/etc/supervisor/supervisord.conf:ro
    command: ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
    healthcheck:
      test: ["CMD", "supervisorctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - separate-services

volumes:
  instances_data:
    driver: local
  supervisor_conf:
    driver: local
  supervisor_logs:
    driver: local
  supervisor_run:
    driver: local

# Example of how to use the Admin API
# 
# 1. Start the services:
#    docker-compose up -d
#
# 2. Wait for the service to be healthy:
#    docker-compose ps
#
# 3. Create a new GOWA instance:
#    curl -X POST "http://localhost:8088/admin/instances" \
#      -H "Authorization: Bearer change-this-to-a-secure-token" \
#      -H "Content-Type: application/json" \
#      -d '{"port": 3001}'
#
# 4. List instances:
#    curl -X GET "http://localhost:8088/admin/instances" \
#      -H "Authorization: Bearer change-this-to-a-secure-token"
#
# 5. Access your GOWA instance:
#    http://localhost:3001
#
# 6. Delete the instance:
#    curl -X DELETE "http://localhost:8088/admin/instances/3001" \
#      -H "Authorization: Bearer change-this-to-a-secure-token"
