name: Release Windows Version

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - '*'

jobs:
  # Build & release Windows 64-bit binary (existing behaviour)
  release-windows-amd64:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Golang Installation
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Golang build (amd64)
        run: |
          cd src && go build -o windows-amd64.exe
      - name: Deploy artifact to release ${{ github.ref_name }} (amd64)
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'src/windows-amd64.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}

  # New: Build & release Windows 32-bit (x86) binary to address Issue #155
  release-windows-386:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest # cross-compile is fine on Linux runners and is faster
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Golang Installation
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
      - name: Golang build (386)
        env:
          GOOS: windows
          GOARCH: 386
        run: |
          cd src && go build -o windows-386.exe
      - name: Deploy artifact to release ${{ github.ref_name }} (386)
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'src/windows-386.exe'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
