name: Release Mac Version

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches-ignore:
      - '*'

jobs:
  release-macos:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: macos-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - name: Golang Installation
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Golang build
        run: |
          cd src && go build -o darwin-amd64
      - name: Deploy artifact to release ${{ github.ref_name }}
        uses: AButler/upload-release-assets@v3.0
        with:
          files: 'src/darwin-amd64'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ github.ref_name }}
